### ISSUE TITLE
runtime error while installing scripts

### ISSUE THREAD

**Issue by daetokonb** [TaylorMouse/warcraft_iii_tools#5]
hey. how i can fix this? (win 10/11, 3dmax 2020/22)
same with ur maxscripts

![daeto](https://user-images.githubusercontent.com/98693878/151699942-68b119e5-0f62-483d-ab34-d7a08999dfbc.png)

**Comment by TaylorMouse** [comment]
fixed that, there was a script pointing to the wrong subfile
